language: node_js
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - chmod +x ./lib/publish.sh
script:
  - yarn lint
  - yarn test
after_success:
  - yarn coverage:publish
  - ./lib/publish.sh
deploy:
  skip_cleanup: true
  provider: script
  script: lib/publish_storybook.sh
  on:
    branch: master
